main: me.VoxelYouTube.ParadoxCore.main.Main
version: 1.0
name: ParadoxCore
author: VoxelYouTube

commands:
  pomoc:
  zasady:
  spawn:
  msg:
  ignore:
  unlock:
  r:
  repair:
  npc:
  broadcast:
  
  
  